// 輸入金鑰
// const CLIENT_ID = "XXXXXXXXXX-XXXXXXXX-XXXX-XXXX";
// const CLIENT_SECRET = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
const CLIENT_ID = "";
const CLIENT_SECRET = "";
export { CLIENT_ID, CLIENT_SECRET };